### Разминка:

In [1]:
import numpy as np

1. Сгенерировать двухмерный массив arr размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  𝑎𝑥+𝑏  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
arr = np.random.uniform(0, 20, (4, 7))
arr
a=1/(arr[3,6]-arr[0,0])
b=0-arr[0,0]*a
arrn=arr*a+b
arrn

array([[ 0.        ,  1.39160429,  0.44358635,  1.46816202,  1.20055791,
         1.22313275, -0.99814099],
       [ 1.15596429, -0.32635415,  1.20828445,  1.38657964,  0.00715393,
         0.4456002 ,  0.12898926],
       [ 0.92147227, -0.2535383 ,  0.21342106, -0.52233956,  0.19861993,
        -0.04874326, -1.07653192],
       [ 0.00796867,  0.74865505, -0.49123077, -0.64383711, -0.4188188 ,
        -0.48599092,  1.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [13]:
a2 = np.random.randint(0, 11, (8, 10))
str=a2.sum(axis=1)
str.argmin(), a2[str.argmin()]


(5, array([1, 1, 2, 2, 1, 0, 9, 0, 5, 7]))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности

In [15]:
p1=np.array((0,0,0))
p2=np.array((3,3,3))
square=np.square(p1-p2)
sum_sq=np.sum(square)
dist=np.sqrt(sum_sq)
dist

5.196152422706632

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [18]:
A=np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
Ainv=np.linalg.inv(A)
Binv=np.linalg.inv(B)
X=np.matmul(np.matmul(Ainv,C), Binv)
X

array([[-1.00000000e+00, -5.32907052e-16],
       [ 2.00000000e+00, -1.00000000e+00],
       [-3.00000000e+00,  4.00000000e+00]])

### Лабораторная работа №1

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.load_txt`. Выведите на экран первые 5 строк массива.

In [2]:
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1)
print(data[:5])

[[1.27244e+05 6.00000e+01 1.60000e+01]
 [2.38910e+04 2.50000e+01 7.00000e+00]
 [9.47460e+04 1.00000e+01 6.00000e+00]
 [6.76600e+04 5.00000e+00 6.00000e+00]
 [1.57911e+05 6.00000e+01 1.40000e+01]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
dataColumns = data[:, 1:]

meanValues = np.mean(dataColumns, axis=0)
minValues = np.min(dataColumns, axis=0)
maxValues = np.max(dataColumns, axis=0)
medianValues = np.median(dataColumns, axis=0)

print("Средние значения:", meanValues)
print("Минимальные значения:", minValues)
print("Максимальные значения:", maxValues)
print("Медианные значения:", medianValues)

Средние значения: [2.16010017e+04 9.05528000e+00]
Минимальные значения: [0. 1.]
Максимальные значения: [2.14748365e+09 3.90000000e+01]
Медианные значения: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
durations1 = data[:, 1]  # Извлекаем столбец с продолжительностью
q_75 = np.percentile(durations1, 75) # Вычисляем 75-й процентиль
durationsLimited = np.clip(durations1, None, q_75) # Ограничиваем значения продолжительности сверху значением q_75
data[:, 1] = durationsLimited
print("Ограниченные значения продолжительности:", durationsLimited)

Ограниченные значения продолжительности: [60. 25. 10. ... 65.  5. 65.]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
durations2 = data[:, 1]  # Извлекаем столбец с продолжительностью
zeroDurationCount = np.sum(durations2 == 0) # Считаем количество рецептов с продолжительностью 0
durations2[durations2 == 0] = 1 # Заменяем нулевые значения на 1
data[:, 1] = durations2
print(f"Количество рецептов с продолжительностью 0: {zeroDurationCount}")

Количество рецептов с продолжительностью 0: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
columns1 = data[:, 1]
uniqueRecipesCount = len (np.unique (columns1))
print(f"Количество уникальных рецептов: {uniqueRecipesCount}")

Количество уникальных рецептов: 65


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
columns2 = data[:, 2]
uniqueIngredientCounts = np.unique(columns2)
print(f"Количество различных значений кол-ва ингредиентов: {len(uniqueIngredientCounts)}")
print("Различные значения кол-ва ингредиентов:", uniqueIngredientCounts)

Количество различных значений кол-ва ингредиентов: 37
Различные значения кол-ва ингредиентов: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 37.
 39.]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
filteredData = data[data[:, 2] <= 5]
print("Рецепты с не более чем 5 ингредиентами:", filteredData)

Рецепты с не более чем 5 ингредиентами: [[4.46597e+05 1.50000e+01 5.00000e+00]
 [2.04134e+05 5.00000e+00 3.00000e+00]
 [2.56230e+04 6.00000e+00 4.00000e+00]
 ...
 [5.20880e+04 6.00000e+01 5.00000e+00]
 [1.28811e+05 1.50000e+01 4.00000e+00]
 [3.70915e+05 5.00000e+00 4.00000e+00]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [22]:
times1 = data[:, 1]  # Время выполнения (минуты)
ingredients1 = data[:, 2]  # Количество ингредиентов
ingredientsPerMinute = ingredients1 / times1 # Вычисляем количество ингредиентов на минуту для каждого рецепта
maxIngredientsPerMinute = np.max(ingredientsPerMinute) # Находим максимальное значение
print("Максимальное количество ингредиентов на минуту:", maxIngredientsPerMinute)

Максимальное количество ингредиентов на минуту: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [23]:
times2 = data[:, 1]  # Время выполнения (минуты)
ingredients2 = data[:, 2]  # Количество ингредиентов
top100indices = np.argsort(times2)[-100:] # Находим индексы топ-100 рецептов с наибольшим временем выполнения
top100ingredients = ingredients2[top100indices] # Извлекаем количество ингредиентов для этих рецептов
averageIngredients = np.mean(top100ingredients) # Вычисляем среднее количество ингредиентов

print("Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:", averageIngredients)

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [25]:
randomIndices = np.random.choice(data.shape[0], size=10, replace=False) # Выбор случайных 10 различных рецептов
randomRecipes = data[randomIndices]
for recipe in randomRecipes:
    print(f"ID: {recipe[0]}, Время выполнения: {recipe[1]} минут, Количество ингредиентов: {recipe[2]}")

ID: 210173.0, Время выполнения: 10.0 минут, Количество ингредиентов: 5.0
ID: 183008.0, Время выполнения: 65.0 минут, Количество ингредиентов: 14.0
ID: 262829.0, Время выполнения: 40.0 минут, Количество ингредиентов: 6.0
ID: 30500.0, Время выполнения: 40.0 минут, Количество ингредиентов: 10.0
ID: 108766.0, Время выполнения: 65.0 минут, Количество ингредиентов: 14.0
ID: 323064.0, Время выполнения: 10.0 минут, Количество ингредиентов: 7.0
ID: 20751.0, Время выполнения: 65.0 минут, Количество ингредиентов: 16.0
ID: 51775.0, Время выполнения: 10.0 минут, Количество ингредиентов: 5.0
ID: 163282.0, Время выполнения: 5.0 минут, Количество ингредиентов: 4.0
ID: 97103.0, Время выполнения: 12.0 минут, Количество ингредиентов: 12.0


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [26]:
ingredientsCount = data[:, 2].astype(int)  # Извлечение количества ингредиентов
averageIngredients = np.mean(ingredientsCount) # Вычисление среднего количества ингредиентов
countBelowAverage = np.sum(ingredientsCount < averageIngredients) # Подсчет количества рецептов с количеством ингредиентов меньше среднего
totalRecipes = ingredientsCount.size # Общее количество рецептов
percentageBelowAverage = (countBelowAverage / totalRecipes) * 100 # Вычисление процента
print(f"Процент рецептов с количеством ингредиентов меньше среднего: {percentageBelowAverage:.2f}%")

Процент рецептов с количеством ингредиентов меньше среднего: 58.80%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [28]:
id = data[:, 0]  # Идентификатор рецепта
cookingTimes = data[:, 1].astype(int)  # Время выполнения в минутах
ingredientsCount = data[:, 2].astype(int)  # Количество ингредиентов
simpleRecipes = ((cookingTimes <= 20) & (ingredientsCount <= 5)).astype(int) # Создание нового столбца для "простых" рецептов
newData = np.column_stack((id, cookingTimes, ingredientsCount, simpleRecipes)) # Объединение данных в новый массив

np.savetxt('simple_recipes_dataset.csv', newData, delimiter=',', fmt='%s', header='ID,cookingTime,ingredientsCount,isSimple', comments='')

13. Выведите процент "простых" рецептов в датасете

In [29]:
totalRecipes = len(simpleRecipes) # Подсчет общего количества рецептов и "простых" рецептов
simpleRecipesCount = np.sum(simpleRecipes)
percentageSimpleRecipes = (simpleRecipesCount / totalRecipes) * 100 # Вычисление процента "простых" рецептов

print(f'Процент "простых" рецептов: {percentageSimpleRecipes:.2f}%')

Процент "простых" рецептов: 9.55%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [33]:
# Группировка рецептов по времени выполнения
shortRecipes = []
standardRecipes = []
longRecipes = []

for i in range(len(cookingTimes)):
    if cookingTimes[i] < 10:
        shortRecipes.append([id[i], cookingTimes[i], ingredientsCount[i]])
    elif 10 <= cookingTimes[i] < 20:
        standardRecipes.append([id[i], cookingTimes[i], ingredientsCount[i]])
    else:
        longRecipes.append([id[i], cookingTimes[i], ingredientsCount[i]])

maxLength = max(len(shortRecipes), len(standardRecipes), len(longRecipes)) # Определение максимального количества рецептов в каждой группе
threeDarray = np.full((3, maxLength, 3), np.nan) # Создание трехмерного массива с заполнением NaN для недостающих значений

for i, recipes in enumerate([shortRecipes, standardRecipes, longRecipes]):
    for j, recipe in enumerate(recipes):
        threeDarray[i, j] = recipe


print('Форма трехмерного массива:', threeDarray.shape)

Форма трехмерного массива: (3, 79751, 3)
